apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-webhook-generic-json
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/rfaircloth-splunk/knative-webhook-generic-json:v1.0.0
          env:
            - name: TARGET
              value: "Python Sample v1"
